[auth.external.google]
enabled = true
client_id = "572829244931-pjluu6imtula89tndekq9fkvbjdnd7uk.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false